package com.tian.model;

import java.io.Serializable;
import java.util.Date;

public class UserBaseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_base_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userBaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.real_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.nick_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.log_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String logPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.pay_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.account_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.account_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.mobile
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.mobile_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String mobileBinding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.mail
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.mail_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String mailBinding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.child_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String childType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.state
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.certificate_card
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String certificateCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.row_add_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.row_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Date rowUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.password_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Date passwordUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.identity_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String identityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.identity_start_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String identityStartNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.identity_end_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String identityEndNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.ex_identity_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String exIdentityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.real_name_authentication
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String realNameAuthentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.pwd_error_count
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Integer pwdErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.change_lock_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private Date changeLockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_level
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.store_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String storeCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.sale_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String saleCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_province
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_city
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_county
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.enterprise_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_register_from
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userRegisterFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_custom_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userCustomType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_custom_type1
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userCustomType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_custom_type2
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String userCustomType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.str_ukeydn
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String strUkeydn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.p2p_user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private String p2pUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base_info
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_base_id
     *
     * @return the value of user_base_info.user_base_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserBaseId() {
        return userBaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_base_id
     *
     * @param userBaseId the value for user_base_info.user_base_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserBaseId(String userBaseId) {
        this.userBaseId = userBaseId == null ? null : userBaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_id
     *
     * @return the value of user_base_info.user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_id
     *
     * @param userId the value for user_base_info.user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_name
     *
     * @return the value of user_base_info.user_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_name
     *
     * @param userName the value for user_base_info.user_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.real_name
     *
     * @return the value of user_base_info.real_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.real_name
     *
     * @param realName the value for user_base_info.real_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.nick_name
     *
     * @return the value of user_base_info.nick_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.nick_name
     *
     * @param nickName the value for user_base_info.nick_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.log_password
     *
     * @return the value of user_base_info.log_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getLogPassword() {
        return logPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.log_password
     *
     * @param logPassword the value for user_base_info.log_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setLogPassword(String logPassword) {
        this.logPassword = logPassword == null ? null : logPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.pay_password
     *
     * @return the value of user_base_info.pay_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.pay_password
     *
     * @param payPassword the value for user_base_info.pay_password
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.account_id
     *
     * @return the value of user_base_info.account_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.account_id
     *
     * @param accountId the value for user_base_info.account_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.account_name
     *
     * @return the value of user_base_info.account_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.account_name
     *
     * @param accountName the value for user_base_info.account_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.mobile
     *
     * @return the value of user_base_info.mobile
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.mobile
     *
     * @param mobile the value for user_base_info.mobile
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.mobile_binding
     *
     * @return the value of user_base_info.mobile_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getMobileBinding() {
        return mobileBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.mobile_binding
     *
     * @param mobileBinding the value for user_base_info.mobile_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setMobileBinding(String mobileBinding) {
        this.mobileBinding = mobileBinding == null ? null : mobileBinding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.mail
     *
     * @return the value of user_base_info.mail
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.mail
     *
     * @param mail the value for user_base_info.mail
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.mail_binding
     *
     * @return the value of user_base_info.mail_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getMailBinding() {
        return mailBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.mail_binding
     *
     * @param mailBinding the value for user_base_info.mail_binding
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setMailBinding(String mailBinding) {
        this.mailBinding = mailBinding == null ? null : mailBinding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.type
     *
     * @return the value of user_base_info.type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.type
     *
     * @param type the value for user_base_info.type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.child_type
     *
     * @return the value of user_base_info.child_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getChildType() {
        return childType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.child_type
     *
     * @param childType the value for user_base_info.child_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setChildType(String childType) {
        this.childType = childType == null ? null : childType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.state
     *
     * @return the value of user_base_info.state
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.state
     *
     * @param state the value for user_base_info.state
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.certificate_card
     *
     * @return the value of user_base_info.certificate_card
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getCertificateCard() {
        return certificateCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.certificate_card
     *
     * @param certificateCard the value for user_base_info.certificate_card
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setCertificateCard(String certificateCard) {
        this.certificateCard = certificateCard == null ? null : certificateCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.row_add_time
     *
     * @return the value of user_base_info.row_add_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.row_add_time
     *
     * @param rowAddTime the value for user_base_info.row_add_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.row_update_time
     *
     * @return the value of user_base_info.row_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.row_update_time
     *
     * @param rowUpdateTime the value for user_base_info.row_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.password_update_time
     *
     * @return the value of user_base_info.password_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Date getPasswordUpdateTime() {
        return passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.password_update_time
     *
     * @param passwordUpdateTime the value for user_base_info.password_update_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setPasswordUpdateTime(Date passwordUpdateTime) {
        this.passwordUpdateTime = passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.identity_name
     *
     * @return the value of user_base_info.identity_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getIdentityName() {
        return identityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.identity_name
     *
     * @param identityName the value for user_base_info.identity_name
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setIdentityName(String identityName) {
        this.identityName = identityName == null ? null : identityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.identity_start_no
     *
     * @return the value of user_base_info.identity_start_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getIdentityStartNo() {
        return identityStartNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.identity_start_no
     *
     * @param identityStartNo the value for user_base_info.identity_start_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setIdentityStartNo(String identityStartNo) {
        this.identityStartNo = identityStartNo == null ? null : identityStartNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.identity_end_no
     *
     * @return the value of user_base_info.identity_end_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getIdentityEndNo() {
        return identityEndNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.identity_end_no
     *
     * @param identityEndNo the value for user_base_info.identity_end_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setIdentityEndNo(String identityEndNo) {
        this.identityEndNo = identityEndNo == null ? null : identityEndNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.ex_identity_no
     *
     * @return the value of user_base_info.ex_identity_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getExIdentityNo() {
        return exIdentityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.ex_identity_no
     *
     * @param exIdentityNo the value for user_base_info.ex_identity_no
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setExIdentityNo(String exIdentityNo) {
        this.exIdentityNo = exIdentityNo == null ? null : exIdentityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.real_name_authentication
     *
     * @return the value of user_base_info.real_name_authentication
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getRealNameAuthentication() {
        return realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.real_name_authentication
     *
     * @param realNameAuthentication the value for user_base_info.real_name_authentication
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setRealNameAuthentication(String realNameAuthentication) {
        this.realNameAuthentication = realNameAuthentication == null ? null : realNameAuthentication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.pwd_error_count
     *
     * @return the value of user_base_info.pwd_error_count
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Integer getPwdErrorCount() {
        return pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.pwd_error_count
     *
     * @param pwdErrorCount the value for user_base_info.pwd_error_count
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setPwdErrorCount(Integer pwdErrorCount) {
        this.pwdErrorCount = pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.change_lock_time
     *
     * @return the value of user_base_info.change_lock_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public Date getChangeLockTime() {
        return changeLockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.change_lock_time
     *
     * @param changeLockTime the value for user_base_info.change_lock_time
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setChangeLockTime(Date changeLockTime) {
        this.changeLockTime = changeLockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_level
     *
     * @return the value of user_base_info.user_level
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_level
     *
     * @param userLevel the value for user_base_info.user_level
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel == null ? null : userLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.store_codes
     *
     * @return the value of user_base_info.store_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getStoreCodes() {
        return storeCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.store_codes
     *
     * @param storeCodes the value for user_base_info.store_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setStoreCodes(String storeCodes) {
        this.storeCodes = storeCodes == null ? null : storeCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.sale_codes
     *
     * @return the value of user_base_info.sale_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getSaleCodes() {
        return saleCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.sale_codes
     *
     * @param saleCodes the value for user_base_info.sale_codes
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setSaleCodes(String saleCodes) {
        this.saleCodes = saleCodes == null ? null : saleCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_province
     *
     * @return the value of user_base_info.user_province
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserProvince() {
        return userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_province
     *
     * @param userProvince the value for user_base_info.user_province
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserProvince(String userProvince) {
        this.userProvince = userProvince == null ? null : userProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_city
     *
     * @return the value of user_base_info.user_city
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_city
     *
     * @param userCity the value for user_base_info.user_city
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity == null ? null : userCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_county
     *
     * @return the value of user_base_info.user_county
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserCounty() {
        return userCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_county
     *
     * @param userCounty the value for user_base_info.user_county
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserCounty(String userCounty) {
        this.userCounty = userCounty == null ? null : userCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.enterprise_type
     *
     * @return the value of user_base_info.enterprise_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.enterprise_type
     *
     * @param enterpriseType the value for user_base_info.enterprise_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setEnterpriseType(String enterpriseType) {
        this.enterpriseType = enterpriseType == null ? null : enterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_register_from
     *
     * @return the value of user_base_info.user_register_from
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserRegisterFrom() {
        return userRegisterFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_register_from
     *
     * @param userRegisterFrom the value for user_base_info.user_register_from
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserRegisterFrom(String userRegisterFrom) {
        this.userRegisterFrom = userRegisterFrom == null ? null : userRegisterFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_custom_type
     *
     * @return the value of user_base_info.user_custom_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserCustomType() {
        return userCustomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_custom_type
     *
     * @param userCustomType the value for user_base_info.user_custom_type
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserCustomType(String userCustomType) {
        this.userCustomType = userCustomType == null ? null : userCustomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_custom_type1
     *
     * @return the value of user_base_info.user_custom_type1
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserCustomType1() {
        return userCustomType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_custom_type1
     *
     * @param userCustomType1 the value for user_base_info.user_custom_type1
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserCustomType1(String userCustomType1) {
        this.userCustomType1 = userCustomType1 == null ? null : userCustomType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_custom_type2
     *
     * @return the value of user_base_info.user_custom_type2
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getUserCustomType2() {
        return userCustomType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_custom_type2
     *
     * @param userCustomType2 the value for user_base_info.user_custom_type2
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setUserCustomType2(String userCustomType2) {
        this.userCustomType2 = userCustomType2 == null ? null : userCustomType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.str_ukeydn
     *
     * @return the value of user_base_info.str_ukeydn
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getStrUkeydn() {
        return strUkeydn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.str_ukeydn
     *
     * @param strUkeydn the value for user_base_info.str_ukeydn
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setStrUkeydn(String strUkeydn) {
        this.strUkeydn = strUkeydn == null ? null : strUkeydn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.p2p_user_id
     *
     * @return the value of user_base_info.p2p_user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public String getP2pUserId() {
        return p2pUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.p2p_user_id
     *
     * @param p2pUserId the value for user_base_info.p2p_user_id
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    public void setP2pUserId(String p2pUserId) {
        this.p2pUserId = p2pUserId == null ? null : p2pUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Wed Sep 06 13:50:49 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userBaseId=").append(userBaseId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", realName=").append(realName);
        sb.append(", nickName=").append(nickName);
        sb.append(", logPassword=").append(logPassword);
        sb.append(", payPassword=").append(payPassword);
        sb.append(", accountId=").append(accountId);
        sb.append(", accountName=").append(accountName);
        sb.append(", mobile=").append(mobile);
        sb.append(", mobileBinding=").append(mobileBinding);
        sb.append(", mail=").append(mail);
        sb.append(", mailBinding=").append(mailBinding);
        sb.append(", type=").append(type);
        sb.append(", childType=").append(childType);
        sb.append(", state=").append(state);
        sb.append(", certificateCard=").append(certificateCard);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", rowUpdateTime=").append(rowUpdateTime);
        sb.append(", passwordUpdateTime=").append(passwordUpdateTime);
        sb.append(", identityName=").append(identityName);
        sb.append(", identityStartNo=").append(identityStartNo);
        sb.append(", identityEndNo=").append(identityEndNo);
        sb.append(", exIdentityNo=").append(exIdentityNo);
        sb.append(", realNameAuthentication=").append(realNameAuthentication);
        sb.append(", pwdErrorCount=").append(pwdErrorCount);
        sb.append(", changeLockTime=").append(changeLockTime);
        sb.append(", userLevel=").append(userLevel);
        sb.append(", storeCodes=").append(storeCodes);
        sb.append(", saleCodes=").append(saleCodes);
        sb.append(", userProvince=").append(userProvince);
        sb.append(", userCity=").append(userCity);
        sb.append(", userCounty=").append(userCounty);
        sb.append(", enterpriseType=").append(enterpriseType);
        sb.append(", userRegisterFrom=").append(userRegisterFrom);
        sb.append(", userCustomType=").append(userCustomType);
        sb.append(", userCustomType1=").append(userCustomType1);
        sb.append(", userCustomType2=").append(userCustomType2);
        sb.append(", strUkeydn=").append(strUkeydn);
        sb.append(", p2pUserId=").append(p2pUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}